version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: postgresql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - go_backend
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: go-rest-api
    environment:
      - DB_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${POSTGRES_PORT}/${DB_TABLE}?sslmode=${SSL_MODE}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
    networks:
      - go_backend

volumes:
  database_postgres:

networks:
  go_backend:
    driver: bridge
