version: "3"

dotenv: ['.env']

tasks:
  # build app binary
  build:
    cmds:
      - go build -o app cmd/server/main.go

  # run containerized up
  run:
    cmds:
      - docker compose up --build

  # create && run migration
  migrate: 
    cmds:
      - docker run --rm -v ./migrations:/migrations --network host --env-file .env migrate/migrate -path /migrations/ -database "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB?sslmode=disable" up

  # drop down current migration
  migrate-down: 
    cmds:
      - docker run --rm -it -v ./migrations:/migrations --network host --env-file .env migrate/migrate -path /migrations/ -database "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB?sslmode=disable" down

  # generate sql-schema to code
  sqlc:
    cmds:
      - docker run --rm -v $(pwd):/src -w /src kjconroy/sqlc generate

  # run adminer
  adminer:
      docker run --rm -ti --network host adminer -d
