DROP TABLE IF EXISTS company;
DROP TABLE IF EXISTS branch;
DROP TABLE IF EXISTS area;
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS contract;
DROP TABLE IF EXISTS paycheck;

