// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Area struct {
	ID          pgtype.UUID
	Name        string
	Description string
}

type Branch struct {
	ID          pgtype.UUID
	Name        string
	Description string
}

type Company struct {
	ID          pgtype.UUID
	Name        string
	Description string
}

type Department struct {
	ID          pgtype.UUID
	Name        string
	Description string
}

type Role struct {
	ID          pgtype.UUID
	Name        string
	Description string
}
